### ISSUE TITLE
PM_data$new error

### ISSUE THREAD

**Issue by AnneCoste** [LAPKB/Pmetrics#176]
Hello,
A data file used for Legacy Pmetrics is not valid for Pmetrics v2, despite using PM_data$new. In the datafile, some additional doses in an EVID=1 row overlap with the timing of an EVID=0. I get a warning reporting unsorted times. ADDL>0 rows are expanded but the unsorted times fail to be sorted and the error file is not edited.
In the datafile, both oral and IV route exist. 
Is there a solution to this problem, without expanding manually all additionnal doses ?
Thank you very much for your attention and for your help.

**Comment by mnneely** [comment]
Hi there, sorry for the trouble. That issue has already been fixed in the beta version 2.1. We hope to release it soon as the next official release. If you’d like to install it now, use this code. Don’t forget to run `PMbuild()` again.

`devtools::install_github(“LAPKB/Pmetrics@dev”)`

I just made a simple test file to verify the fix. Let me know if I didn’t capture your problem in the test and if the beta version doesn’t fix it.

[test.csv](https://github.com/LAPKB/Pmetrics/files/12109602/test.csv)

**Comment by AnneCoste** [comment]
Dear Dr Neely,

Thank you very much for your answer, the new version works correctly with your example.
However, since I did not get the same RUN results with my dataset than with the previous version, I looked more into it and I noticed some errors in the edited data file when using PM_data$new.

Here are two examples, with the created datafile (named “output” ):

-          Ex 1 : one dose administration is created at time 326 also I did not specify dose administration after time 182

-          Ex 2 : many doses are created after time 252 also I did not specify any, and some doses administration are missing between time 132 and 252.

Thank you again for the very interesting workshop in Lyon, it was really great !!

Sincerely yours,

Anne Coste


Dr Anne Coste – CCU-AH
Service de maladies infectieuses
CHRU de Brest
Tel : 02 30 33 79 67

De : Michael Neely ***@***.***
Envoyé : jeudi 20 juillet 2023 15:42
À : LAPKB/Pmetrics ***@***.***>
Cc : COSTE ANNE ***@***.***>; Author ***@***.***>
Objet : Re: [LAPKB/Pmetrics] PM_data$new error (Issue #176)


ATTENTION: Cet e-mail provient d’une adresse mail extérieure au CHU de Brest. Ne cliquez pas sur les liens ou n'ouvrez pas les pièces jointes à moins de connaître l'expéditeur et de savoir que le contenu est sûr. Cliquez ici<https://www.mailcontrol.com/sr/Gdc8on_5CvzGX2PQPOmvUt_pSVNK13NsMWf9j1ndsocTmuyK0knEuhK02b8BujA4--IQ3lHAulsoKRuEdgZyEA==> si vous considérez ce mail comme étant un spam. Merci de votre vigilance.


Hi there, sorry for the trouble. That issue has already been fixed in the beta version 2.1. We hope to release it soon as the next official release. If you’d like to install it now, use this code. Don’t forget to run PMbuild() again.

***@***.***”)

I just made a simple test file to verify the fix. Let me know if I didn’t capture your problem in the test and if the beta version doesn’t fix it.

test.csv<https://github.com/LAPKB/Pmetrics/files/12109602/test.csv>

**Comment by mnneely** [comment]
Can you email me your data file so we can figure out what’s wrong?  You can send to mneely@usc.edu. I won’t share it outside our group. We just need it for debugging purposes.  Thanks.

**Comment by AnneCoste** [comment]
Dear Dr Neely,

I am sorry to bother you again. I downloaded the latest version today and tried again but it still doesn't work.

Could you please give me a link to download legacy pmetrics? I really need to work and make progress on my PhD.

Thank you again for the wonderful workshop in Lyon!

Sincerely yours,

Anne Coste



Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Trepon** [comment]
Hi Anne,

Older versions are available on the releases page : [https://github.com/LAPKB/Pmetrics/releases?page=1](https://github.com/LAPKB/Pmetrics/releases?page=1)

Ronan

**Comment by mhovd** [comment]
@AnneCoste, were you able to download a previous version that worked for you?
Or do you need any help with manual expansion of the doses, if the current solution does not work?

**Comment by mnneely** [comment]
Oh, I'm so sorry. This one got away from me. I just fixed the bug I believe. Can you try version 2.1.1 in the dev branch? 

`devtools::install_github("LAPKB/Pmetrics@dev")`

**Comment by mhovd** [comment]
I am closing this issue due to inactivity, but please let us know if the issue still persists and was not solved with the solution Michael provided.

**Comment by AnneCoste** [comment]
The issue was fixed, thank you very much.

________________________________
De : Markus Hovd ***@***.***>
Envoyé : vendredi 17 janvier 2025 07:48:04
À : LAPKB/Pmetrics
Cc : COSTE Anne; Mention
Objet : Re: [LAPKB/Pmetrics] PM_data$new error (Issue #176)


MESSAGE EXTERNE : Vérifier impérativement les expéditeurs avant de cliquer sur un lien ou ouvrir une pièce jointe. En cas de doute, contactez la Centrale d'Appels via le Portail<https://portail-demande.chu-brest.fr/servicedesk/customer/portal/2/user/login?destination=portal%2F2>.



Closed #176<https://github.com/LAPKB/Pmetrics/issues/176> as completed.
